// ******************************************************************
//       /\ /|       @file       MainWindow
//       \ V/        @brief      auto generated by UIBinder
//       | "")       @author     Shadowrabbit, yingtu0401@gmail.com
//       /  |                    
//      /  \         @Modified   2024/2/24 19:34:29
//    *(__\_\        @Copyright  Copyright (c) 2024, Shadowrabbit
// ******************************************************************

using UnityEngine;
using UnityEngine.UI;

namespace Rabi
{
	public partial class MainWindow
	{
		private Button _btnInfo;
		private Text _txtInfo;
		private Button _btnPlay;
		private Text _txtPlay;
		private Button _btnSetting;
		private Text _txtSetting;

		private void GetBindComponents(GameObject go)
		{
			var uiBinder = go.GetComponent<UIBinder>();
			_btnInfo = uiBinder.GetBindComponent<Button>(0);
			_txtInfo = uiBinder.GetBindComponent<Text>(1);
			_btnPlay = uiBinder.GetBindComponent<Button>(2);
			_txtPlay = uiBinder.GetBindComponent<Text>(3);
			_btnSetting = uiBinder.GetBindComponent<Button>(4);
			_txtSetting = uiBinder.GetBindComponent<Text>(5);
		}
	}
}
